# This is a basic workflow to help you get started with Actions

name: Incorporate latest official

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 23 27 5 *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
# | awk '{printf $1}
    # Runs a set of commands using the runners shell
    - name: Download latest official source code
      run: |
        mkdir ./official
        wget -O oactobjs32.zip https://www.ssa.gov/OACT/anypia/download/oactobjs32.zip
        wget -O source32.zip https://www.ssa.gov/OACT/anypia/download/source32.zip
        unzip source32.zip -d ./official
        unzip oactobjs32.zip -d ./official
        ls -lah ./official/
        shasum -a 256 ./oactobjs32.zip
        shasum -a 256 ./source32.zip
        ls -lah .
        
